name: 'android-ci'
description: 'An image for building Android apps with support for multiple SDK Build Tools. This Docker image contains the Android SDK and most common packages necessary for building Android apps in a CI tool.'
author: 'code0987 <durgapalneeraj@gmail.com>'
branding:
  icon: 'box'
  color: 'green'

runs:
  using: 'docker'
  image: 'Dockerfile'
