name: 'android-ci-github-action'
description: 'A github action for image for building Android apps with support for multiple SDK Build Tools.'
author: 'code0987 <durgapalneeraj@gmail.com>'
branding:
  icon: 'box'
  color: 'green'

runs:
  using: 'docker'
  image: 'Dockerfile'
